In [2]:
import numpy as np

In [3]:
np.mean([34,32,54,65,23])

41.6

In [4]:
np.median([3,4,6,7,3,9,5])

5.0

In [ ]:
# pip install pandas

In [6]:
import pandas as pd

In [13]:
d = {'A':[1,2,3,4,5], 'B':[100,200,300,400,500]}

In [14]:
pd.DataFrame(d)

   A    B
0  1  100
1  2  200
2  3  300
3  4  400
4  5  500

In [20]:
pd.read_csv('addresses.csv')

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [26]:
pd.read_csv('addresses.csv',names=['A','B','C','D','E','F','G','H','I'],)

,A,B,C,D,E,F,G,H,I
0,id,location_id,address_1,address_2,city,state_province,postal_code,country,NaN
1,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US,NaN
2,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US,NaN
3,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US,NaN
4,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US,NaN
5,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US,NaN
6,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US,NaN
7,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US,NaN
8,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US,NaN
9,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US,NaN
10,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US,NaN
11,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US,NaN
12,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US,NaN
13,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US,NaN
14,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US,NaN
15,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US,NaN
16,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US,NaN
17,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US,NaN
18,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US,NaN
19,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US,NaN
20,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US,NaN
21,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US,NaN

In [27]:
pd.read_csv('addresses.csv')

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [28]:
data = pd.read_csv('addresses.csv')

In [29]:
data

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [30]:
data.head()

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US

In [31]:
data.tail()

,id,location_id,address_1,address_2,city,state_province,postal_code,country
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [ ]:
data.sample